from io import BytesIO

import pytest
from file_process.exceptions import DelimiterError
from numpy import nan
import pandas as pd

from file_process.txt.txt_processor import TxtFileProcessor
from tests.test_file_process import get_remote_file_obj, TXT_INPUT_FILES_PATH


class TestTxtFileProcessor:
    original_data_path = f'{TXT_INPUT_FILES_PATH}/txt_example.txt'
    fasta_data_path = f'{TXT_INPUT_FILES_PATH}/fasta_example.fasta'
    pdb_data_path = f'{TXT_INPUT_FILES_PATH}/pdb_example.pdb'

    def _get_file_and_remote_file_obj(self, path: str):
        file = open(path, 'rb')
        file_obj = BytesIO(file.read())
        return file, file_obj

    def test_read_file(self):
        file_bytes_io = get_remote_file_obj(self.original_data_path)
        res = TxtFileProcessor(file_bytes_io)
        assert isinstance(res.txt_data, str)

    def test_get_preview(self):
        file_bytes_io = get_remote_file_obj(self.original_data_path)
        file_processor = TxtFileProcessor(file_bytes_io)
        _, _, _, text_file_preview = file_processor.get_preview()

        assert text_file_preview == """IQGIZBXAZYBADFENHMYLCWYTCOLEZQTEBIMAFMGGOBMHIBCBMPCPXCXHHZLWGNMAYCXLCVMOFVNBRFPIGYNWDMOCMVHNUITUHGZKZFQ
HONIYRGFSELKIWFCKUUQQTFORXFVCFHDVUASLZOTLYDCSDFVUOBIOFQCONFSQIFWOAFMYBLBAISKUTRNDZGNVLUFGREFOYUZFLRRIUMQYTNXKEGPDYSWSOEPDXBPPMNTHQQUV
NKXGOOKSCAMBZHICNBERBOSAVNWNHZKQRYIGSSYXVRIDKLTBUUCRBIETKQPPWH
IDZQWHUHWNRRDAMZGSKHDXYRAOLWFQOKQCFOZFUGAHGUFFTIWFHOGICAUMZHEFEXARPYIGHSQTOAKBCVAUKIOWHSXWLWHHRBEQMWWXEHKRVLIAFACKWNALZPLRIYLASOVDFHMWVIULQQRXRONRPOCRIATOFYVCHABWDBH
KVOHKZBVHQBCFGTQLEVXUHOZTCYQBGMCZFROTWLMMIMIBQEKYRLSOUUMUXPTWHUKDIAVRPKGAKLOVGCUGBROTSBKWTEQFYPMSUAVTILHUQFNDNEMYOYXNAKYMOOOCTYYNFCWRKZNURYWZGFMFRATXNTFVEQ
WCKWXNOGLETGINPIHOHVFLCWQFDFWIAPNHQMQQGEOBGBGRDOSPDVNTSZEXGQXULKVXFBDIMEVFPT
HYXKWZVDOTPTBKYTBAFZADFUAHGHECAKSCOIDCKCQXCDIWGZVTQV
TUKCQCELLPYYLQHHZLNRHSFMXOXNTSEHLTFLXVKYXPMRUISWODSTQCHRDBMEHIHHKNSVCBBYVBXHQXHQKAUWDSMHQDQCDKPBEPZALQPCDGDMULLRFZRAIKLAILHLEIDANDEWKAMXILUOQNYEMCXSQVHFDXXUDBZBFOKZPAXO
KDEDLUWLVNQEQITPASXHUSNNMDLAKRZMZPQVAWKYRSYVEGWBDX
FEZGFYHRUOZMTHSYWYCBRLEBQHPLHRHUCTVOGBUMIPTGHVRDTGTEHFCSTAYQXICYTFCWSHRNFFBAESFS
TTOFMSBNXMSQCOFLCIIWB
UZPGDORLDTYFUGHOWXPZOAXMVGKLGGMKPCGPYUDMGPVSUWQFTPSTYNEMVLCPIVEOPKFAPZLRWTPDCWEESGHRNEWMWMZTTZXZTRMDDMKHFGNKCOGETYBYNTFXYXSGSILPDLCWCEWZVFDIXCYGUHKYKZCHNASUICQPTPXZHIOYAZNCFGXTNDNRXRAAPWBZVB
HRBHHSVRNQPHUNHGIHKFEQZF
ECTAOQUHZNQLVDDPQWZLYBQYHSXOMIBIDCSSSPIKGUQCKAGGFOYXGZKPZTDZHEWRWEDYAOGWWUYGSTOLXOUTELRXPGVAWLYOFDPIAHDAWPAVBCWYHZXXWXDEOSNTAXCKAEZFBRPPWTUMURZOXPLRZZTHVRDVXUNRTUOVOAQ
FORMONWBVXWEZWKMB"""
